version: '3.1'

services:

  api:
    image: node
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./code:/home/node/app
    ports:
      - 8080:3000
    command: "npm start"
    environment:
      - PORT=3000
      - GOOGLE_MAPS_DIRECTIONS_API_KEY=${GOOGLE_MAPS_DIRECTIONS_API_KEY}

